package com.blog.util;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Scanner;

/**
 * One-time utility tool to generate encrypted secrets.
 * 
 * This tool:
 * 1. Generates a new AES-256 secret key
 * 2. Encrypts sensitive values (database password, JWT secret, API keys, etc.)
 * 3. Saves encrypted values to secrets.enc file or prints to console
 * 
 * Usage:
 *   java -cp <classpath> com.blog.util.GenerateEncryptedSecrets
 * 
 * The secret key will be printed to console and should be saved securely.
 * Store it either:
 * - As an environment variable: APP_SECRET_KEY
 * - In a secure file: /etc/myapp/secret.key (or custom path)
 * 
 * @author Blog Management System
 * @version 1.0
 */
public class GenerateEncryptedSecrets {

    private static final String SECRETS_FILE = "secrets.enc";
    private static final String SECRET_KEY_FILE = "secret.key";

    public static void main(String[] args) {
        System.out.println("=========================================");
        System.out.println("  Encrypted Secrets Generator Tool");
        System.out.println("=========================================\n");

        try {
            // Generate secret key
            System.out.println("Generating AES-256 secret key...");
            String secretKey = CryptoUtil.generateSecretKey();
            System.out.println("\n✅ Secret Key Generated Successfully!");
            System.out.println("\n" + "=".repeat(50));
            System.out.println("SECRET KEY (SAVE THIS SECURELY):");
            System.out.println("=".repeat(50));
            System.out.println(secretKey);
            System.out.println("=".repeat(50));
            System.out.println("\n⚠️  IMPORTANT: Save this key in one of these ways:");
            System.out.println("   1. Environment variable: export APP_SECRET_KEY=\"" + secretKey + "\"");
            System.out.println("   2. Secure file: echo \"" + secretKey + "\" > /etc/myapp/secret.key");
            System.out.println("   3. Or save in: " + SECRET_KEY_FILE + " (will be added to .gitignore)\n");

            // Ask user if they want to save the key to a file
            Scanner scanner = new Scanner(System.in);
            System.out.print("Save secret key to " + SECRET_KEY_FILE + "? (y/n): ");
            String saveKey = scanner.nextLine().trim().toLowerCase();
            
            if (saveKey.equals("y") || saveKey.equals("yes")) {
                try {
                    Files.write(Paths.get(SECRET_KEY_FILE), secretKey.getBytes());
                    System.out.println("✅ Secret key saved to " + SECRET_KEY_FILE);
                    System.out.println("⚠️  Remember to set proper file permissions: chmod 600 " + SECRET_KEY_FILE + "\n");
                } catch (IOException e) {
                    System.err.println("❌ Failed to save secret key to file: " + e.getMessage());
                }
            }

            // Collect sensitive values from user
            System.out.println("\nEnter sensitive values to encrypt (press Enter to skip):\n");
            
            String dbPassword = promptValue(scanner, "Database Password");
            String dbUsername = promptValue(scanner, "Database Username (optional)");
            String jwtSecret = promptValue(scanner, "JWT Secret");
            String mailPassword = promptValue(scanner, "Mail/SMTP Password");
            String mailUsername = promptValue(scanner, "Mail/SMTP Username (optional)");
            String apiKey = promptValue(scanner, "API Key (optional)");

            // Encrypt values
            System.out.println("\nEncrypting values...\n");
            StringBuilder secretsContent = new StringBuilder();
            secretsContent.append("# Encrypted Secrets File\n");
            secretsContent.append("# Generated by GenerateEncryptedSecrets tool\n");
            secretsContent.append("# DO NOT COMMIT THIS FILE TO VERSION CONTROL\n");
            secretsContent.append("# The secret key must be provided via APP_SECRET_KEY env var or secret.key file\n\n");

            if (dbPassword != null && !dbPassword.isEmpty()) {
                String encrypted = CryptoUtil.encrypt(dbPassword, secretKey);
                secretsContent.append("db.password.encrypted=").append(encrypted).append("\n");
                System.out.println("✅ Database password encrypted");
            }

            if (dbUsername != null && !dbUsername.isEmpty()) {
                String encrypted = CryptoUtil.encrypt(dbUsername, secretKey);
                secretsContent.append("db.username.encrypted=").append(encrypted).append("\n");
                System.out.println("✅ Database username encrypted");
            }

            if (jwtSecret != null && !jwtSecret.isEmpty()) {
                String encrypted = CryptoUtil.encrypt(jwtSecret, secretKey);
                secretsContent.append("jwt.secret.encrypted=").append(encrypted).append("\n");
                System.out.println("✅ JWT secret encrypted");
            }

            if (mailPassword != null && !mailPassword.isEmpty()) {
                String encrypted = CryptoUtil.encrypt(mailPassword, secretKey);
                secretsContent.append("mail.password.encrypted=").append(encrypted).append("\n");
                System.out.println("✅ Mail password encrypted");
            }

            if (mailUsername != null && !mailUsername.isEmpty()) {
                String encrypted = CryptoUtil.encrypt(mailUsername, secretKey);
                secretsContent.append("mail.username.encrypted=").append(encrypted).append("\n");
                System.out.println("✅ Mail username encrypted");
            }

            if (apiKey != null && !apiKey.isEmpty()) {
                String encrypted = CryptoUtil.encrypt(apiKey, secretKey);
                secretsContent.append("api.key.encrypted=").append(encrypted).append("\n");
                System.out.println("✅ API key encrypted");
            }

            // Save to file or print to console
            System.out.print("\nSave encrypted secrets to " + SECRETS_FILE + "? (y/n): ");
            String saveSecrets = scanner.nextLine().trim().toLowerCase();

            if (saveSecrets.equals("y") || saveSecrets.equals("yes")) {
                try {
                    Files.write(Paths.get(SECRETS_FILE), secretsContent.toString().getBytes());
                    System.out.println("✅ Encrypted secrets saved to " + SECRETS_FILE);
                } catch (IOException e) {
                    System.err.println("❌ Failed to save secrets file: " + e.getMessage());
                }
            } else {
                System.out.println("\n" + "=".repeat(50));
                System.out.println("ENCRYPTED SECRETS (Add to application.properties):");
                System.out.println("=".repeat(50));
                System.out.println(secretsContent.toString());
            }

            // Print summary
            System.out.println("\n" + "=".repeat(50));
            System.out.println("SUMMARY");
            System.out.println("=".repeat(50));
            System.out.println("✅ Secret key generated");
            System.out.println("✅ Secrets encrypted");
            System.out.println("\nNext steps:");
            System.out.println("1. Store the secret key securely (env var or file)");
            System.out.println("2. Add encrypted properties to application.properties");
            System.out.println("3. Update Spring Boot config to use CryptoService for decryption");
            System.out.println("4. Ensure " + SECRET_KEY_FILE + " and " + SECRETS_FILE + " are in .gitignore\n");

        } catch (CryptoUtil.CryptoException e) {
            System.err.println("❌ Encryption error: " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            System.err.println("❌ Unexpected error: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * Prompts user for a sensitive value.
     * 
     * @param scanner Scanner instance
     * @param label Label for the prompt
     * @return User input or null if skipped
     */
    private static String promptValue(Scanner scanner, String label) {
        System.out.print(label + ": ");
        String value = scanner.nextLine().trim();
        return value.isEmpty() ? null : value;
    }
}
